/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 1.2 */
/* C:\lscc\diamond\3.13\ispfpga\bin\nt64\scuba.exe -w -n pwr_cntrllr -lang verilog -synth lse -bus_exp 7 -bb -arch xo2c00 -type power_cntl -entry USER_CFG -s2s BYPASS -wake USER -standby -bandgap_off -por_off  */
/* Tue Oct 15 17:58:04 2024 */


`timescale 1 ns / 1 ps
module pwr_cntrllr (USERSTDBY, CLRFLAG, CFGSTDBY, STDBY, SFLAG)/* synthesis NGD_DRC_MASK=1 */;
    input wire USERSTDBY;
    input wire CLRFLAG;
    input wire CFGSTDBY;
    output wire STDBY;
    output wire SFLAG;

    wire scuba_vlo;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam PCNTR_Inst0.BGOFF = "TRUE" ;
    defparam PCNTR_Inst0.POROFF = "TRUE" ;
    defparam PCNTR_Inst0.WAKEUP = "USER" ;
    defparam PCNTR_Inst0.TIMEOUT = "BYPASS" ;
    defparam PCNTR_Inst0.STDBYOPT = "USER_CFG" ;
    PCNTR PCNTR_Inst0 (.CLK(scuba_vlo), .USERTIMEOUT(scuba_vlo), .USERSTDBY(USERSTDBY), 
        .CLRFLAG(CLRFLAG), .CFGWAKE(scuba_vlo), .CFGSTDBY(CFGSTDBY), .STDBY(STDBY), 
        .STOP(), .SFLAG(SFLAG));



    // exemplar begin
    // exemplar end

endmodule
