/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.13.0.56.2 */
/* Module Version: 1.2 */
/* Tue Oct 15 17:53:29 2024 */

/* parameterized module instance */
pwr_ctrllr __ (.USERSTDBY( ), .CLRFLAG( ), .CFGSTDBY( ), .STDBY( ), 
    .SFLAG( ));
